name: LobbySystem
author: FinnFilu
version: 1.0
main: de.finnfilu.lobbysystem.Main.Main

commands:
  setwarp:
  warp:
    aliases: [spawn, lobby, l, hub]
  gamemode:
    aliases: [gm]
  chatclear:
    aliases: [cc]
  fly:
  slowchat:
    aliases: [sc]
  teleport:
    aliases: [tp]
  teleporthere:
    aliases: [tphere]